### PR TITLE
fix english and typos

### PR DESCRIPTION
**Pull request by michaelkonecny**
Thanks for the great tutorial.

Sorry for the separated pull requests. Only now I created a local clone.

### CODE REVIEW

**Comment by sylvaticus** [comment]
Thanks to you. I plane to add new stuff soon. I would also like to add things from by book, but I don't have the permissions of the publisher :-/

**Comment by michaelkonecny** [comment]
That's a shame. However the tutorial is already quite nice. A nice kick
start.

Where in Italy are you located, btw?

**Comment by sylvaticus** [comment]
I'm actually living in France.

**Comment by michaelkonecny** [comment]
Ah, sorry.

I'm going to Italy in 2 weeks and I'm going to have a lot of free time, so
I was going to propose a coffee.

**Pull request merged**
